import type { Service } from "./types";

// Business Registration & Incorporation — the 6 entity-formation services
// from the site's original REG category. Not part of the original 57-item
// audit list, but every other service card on the site now links to a
// dedicated page, so these get the same treatment for consistency.

export const BUSINESS_REGISTRATION_SERVICES: Service[] = [
  {
    slug: "private-limited-company",
    title: "Private Limited Company",
    categoryId: "business-registration",
    categoryLabel: "Business Registration & Incorporation",
    code: "REG-01",
    coverage: "existing",
    shortDescription:
      "Incorporate a Private Limited Company — India's most preferred structure for funded startups and growing businesses.",
    heroHeadline: "A structure built for growth, funding and credibility.",
    heroSupport:
      "We handle DSC, DIN, name approval, incorporation filing, PAN/TAN and the day-one compliances that follow — so your company is legally ready to operate and raise capital.",
    description: [
      "A Private Limited Company is a separate legal entity with limited liability for its shareholders, registered under the Companies Act, 2013. It's the structure most investors, banks and larger buyers expect to see, which makes it the default choice for startups planning to raise funding or scale.",
      "Because it's a distinct legal person, the company can own assets, enter contracts, sue and be sued in its own name — and shareholders are generally not personally liable for the company's debts beyond their shareholding.",
      "Gurur Consultancy manages the incorporation process end-to-end — digital signatures, director identification, name approval, the SPICe+ filing itself, and the immediate post-incorporation steps needed before the company can legally start operating.",
    ],
    benefits: [
      "Limited liability — shareholders' personal assets are protected from company debts",
      "Separate legal identity, distinct from its founders and directors",
      "Easier access to equity funding — most investors require this structure",
      "Perpetual succession — the company continues regardless of changes in shareholding",
      "Greater credibility with banks, larger customers and government buyers",
    ],
    whoNeedsIt: [
      "Startups planning to raise equity funding from investors",
      "Founders who want limited liability protection as the business scales",
      "Businesses that need a formal corporate structure to bid for larger contracts or government tenders",
      "Two or more founders who want defined shareholding and governance from day one",
    ],
    eligibility: [
      "Requires a minimum of two directors and two shareholders (can be the same individuals), with at least one resident director",
      "No minimum paid-up capital requirement under current law, though a realistic starting capital is advisable",
      "A registered office address in India is required at the time of incorporation",
    ],
    documents: [
      "PAN and Aadhaar of all proposed directors and shareholders",
      "Passport-size photographs and address proof (bank statement/utility bill) of directors",
      "Proof of registered office — rent agreement or ownership document plus a No Objection Certificate",
      "Digital Signature Certificates for all proposed directors",
      "Proposed company name options for approval",
    ],
    documentsNote: "Commonly required documents may include:",
    process: [
      { title: "Consultation", description: "We understand your business, founding team and shareholding plan to confirm this is the right structure." },
      { title: "DSC & DIN", description: "Digital Signature Certificates and Director Identification Numbers are obtained for all proposed directors." },
      { title: "Name Approval", description: "We reserve your company name through the SPICe+ Part A name-approval process." },
      { title: "Incorporation Filing", description: "SPICe+ Part B is filed with the MCA along with MOA, AOA and supporting documents." },
      { title: "PAN & TAN Allotment", description: "PAN and TAN are allotted along with incorporation, linked to the new company." },
      { title: "Post-Incorporation Compliance", description: "We assist with Commencement of Business (INC-20A) filing and registered-office verification (INC-22)." },
    ],
    faqs: [
      { question: "What is a Private Limited Company?", answer: "A separate legal entity registered under the Companies Act, 2013, offering limited liability to its shareholders and a formal corporate structure." },
      { question: "How many people are needed to start one?", answer: "A minimum of two directors and two shareholders are required — the same individuals can hold both roles." },
      { question: "Is there a minimum capital requirement?", answer: "No minimum paid-up capital is mandated under current law, though most companies start with a realistic working capital figure." },
      { question: "What documents are required?", answer: "PAN, Aadhaar and address proof of directors/shareholders, registered office proof, and Digital Signature Certificates — the exact list can vary slightly by case." },
      { question: "Can incorporation be done fully online?", answer: "Yes. Name approval and incorporation filing are done through the MCA's SPICe+ portal." },
      { question: "What happens right after incorporation?", answer: "The company receives its Certificate of Incorporation, PAN and TAN, and typically needs to file Commencement of Business (INC-20A) before starting operations." },
      { question: "Do I need GST or MSME registration too?", answer: "Not automatically — these are separate registrations that apply based on your business activity and turnover. We can advise on which apply to you." },
    ],
    relatedServices: ["one-person-company", "llp-registration", "digital-signature-certificate", "gst-registration", "msme-udyam-registration"],
    ctaDescription: "Tell us about your founding team and plans, and we'll confirm whether a Private Limited Company is the right fit and take the filing forward.",
  },
  {
    slug: "one-person-company",
    title: "One Person Company (OPC)",
    categoryId: "business-registration",
    categoryLabel: "Business Registration & Incorporation",
    code: "REG-02",
    coverage: "existing",
    shortDescription:
      "Register a One Person Company — a private limited structure for a single founder, without needing a co-founder.",
    heroHeadline: "Corporate structure, limited liability, single founder.",
    heroSupport:
      "We handle the nominee arrangement, name approval and incorporation filing so a solo founder gets the benefits of a company structure without needing a second shareholder.",
    description: [
      "A One Person Company (OPC) is a private company that can be incorporated with a single member, introduced under the Companies Act, 2013 specifically for solo entrepreneurs who want limited liability without bringing in a co-founder.",
      "It combines the operational simplicity a sole founder wants with the legal separation and limited liability protection of a company structure — the founder's personal assets stay protected from business liabilities.",
      "Gurur Consultancy manages the nominee director/member requirement, name approval and incorporation filing, and explains the conditions under which an OPC must later convert to a private or public company.",
    ],
    benefits: [
      "Limited liability protection for a single founder",
      "Full control — one person holds all shares and typically also acts as director",
      "Separate legal identity distinct from the founder personally",
      "Simpler compliance structure than a multi-shareholder private company",
      "Credibility of a registered company for banking, contracts and vendor onboarding",
    ],
    whoNeedsIt: [
      "Solo entrepreneurs who want limited liability without a co-founder",
      "Freelancers and consultants transitioning into a formal business structure",
      "Founders not yet ready to bring in a second shareholder but wanting company-level credibility",
    ],
    eligibility: [
      "Only a natural person who is an Indian citizen and resident in India can incorporate an OPC or act as its nominee",
      "An OPC must nominate another individual as a nominee member, who steps in if the sole member is unable to continue",
      "Certain turnover/capital thresholds trigger mandatory conversion to a private or public company — confirmed at the time of filing",
    ],
    documents: [
      "PAN and Aadhaar of the proposed member and nominee",
      "Passport-size photograph and address proof of both",
      "Proof of registered office with NOC from the owner, where applicable",
      "Digital Signature Certificate for the proposed director",
      "Consent of the nominee in the prescribed format",
    ],
    documentsNote: "Commonly required documents may include:",
    process: [
      { title: "Consultation", description: "We confirm an OPC fits your situation and explain the nominee requirement." },
      { title: "DSC & Name Approval", description: "Digital Signature Certificate is obtained and the company name is reserved via SPICe+ Part A." },
      { title: "Incorporation Filing", description: "SPICe+ Part B is filed with the nominee's consent and supporting documents." },
      { title: "PAN & TAN Allotment", description: "PAN and TAN are issued along with the incorporation certificate." },
      { title: "Post-Incorporation Steps", description: "We assist with the initial compliance filings needed before commencing business." },
    ],
    faqs: [
      { question: "What is a One Person Company?", answer: "A private company that can be formed with a single member, giving a solo founder limited liability and a separate legal identity." },
      { question: "Why does an OPC need a nominee?", answer: "The nominee steps in as the member if the sole founder becomes incapacitated or passes away, so the company can continue." },
      { question: "Can an OPC have more than one director?", answer: "Yes — an OPC can appoint additional directors for day-to-day management even though it has only one member/shareholder." },
      { question: "Does an OPC ever have to convert to a private company?", answer: "Yes, once it crosses certain turnover or capital thresholds, conversion becomes mandatory — we can confirm current thresholds when you're ready to file." },
      { question: "Who can be the nominee?", answer: "Only an Indian citizen and resident, with their written consent in the prescribed format." },
      { question: "How is this different from a sole proprietorship?", answer: "A proprietorship has no separate legal identity and unlimited personal liability; an OPC is a registered company with limited liability, at the cost of more formal compliance." },
    ],
    relatedServices: ["private-limited-company", "proprietorship-registration", "digital-signature-certificate", "gst-registration"],
    ctaDescription: "Tell us about your business, and we'll confirm whether an OPC or another structure suits you best before filing.",
  },
  {
    slug: "llp-registration",
    title: "LLP Registration",
    categoryId: "business-registration",
    categoryLabel: "Business Registration & Incorporation",
    code: "REG-03",
    coverage: "existing",
    shortDescription:
      "Register a Limited Liability Partnership — the operational flexibility of a partnership with the limited liability of a company.",
    heroHeadline: "Partnership flexibility, company-level liability protection.",
    heroSupport:
      "We handle DPIN, name approval through RUN-LLP, incorporation and the LLP Agreement — so your partnership is registered correctly from the start.",
    description: [
      "A Limited Liability Partnership (LLP) is a hybrid structure registered under the LLP Act, 2008 that combines the operational flexibility of a traditional partnership with limited liability protection for its partners — similar to a company.",
      "Each partner's liability is limited to their agreed contribution, and one partner isn't personally liable for another partner's misconduct or independent actions — a meaningful difference from a traditional partnership firm.",
      "Gurur Consultancy manages partner DPIN allotment, name reservation, incorporation filing and drafting of the LLP Agreement that governs how the partnership actually operates.",
    ],
    benefits: [
      "Limited liability for partners, unlike a traditional partnership firm",
      "Lower compliance burden compared to a private limited company",
      "No minimum capital contribution requirement",
      "Separate legal entity that can hold property and enter contracts in its own name",
      "Flexible internal management structure defined by the LLP Agreement",
    ],
    whoNeedsIt: [
      "Professional firms — consultants, designers, service providers — with two or more partners",
      "Family-run or partner-run businesses wanting liability protection without full company compliance",
      "Businesses that don't currently need external equity funding (LLPs can't issue shares)",
    ],
    eligibility: [
      "Requires a minimum of two partners, with at least two designated partners, one of whom must be resident in India",
      "No minimum capital contribution is mandated",
      "Not suitable if you plan to raise equity funding from investors — an LLP cannot issue shares",
    ],
    documents: [
      "PAN and Aadhaar of all partners",
      "Address proof and photographs of designated partners",
      "Proof of registered office with NOC where applicable",
      "Digital Signature Certificates for designated partners",
      "Proposed LLP name options and draft LLP Agreement terms",
    ],
    documentsNote: "Commonly required documents may include:",
    process: [
      { title: "Consultation", description: "We confirm an LLP fits your partnership structure and funding plans." },
      { title: "DSC & DPIN", description: "Digital Signature Certificates and Designated Partner Identification Numbers are obtained." },
      { title: "Name Reservation", description: "The LLP name is reserved through the RUN-LLP service." },
      { title: "Incorporation Filing", description: "The FiLLiP incorporation form is filed with the Registrar along with supporting documents." },
      { title: "LLP Agreement", description: "We draft and help file the LLP Agreement, which governs profit-sharing, roles and partner rights." },
      { title: "PAN & TAN Allotment", description: "PAN and TAN are obtained for the newly incorporated LLP." },
    ],
    faqs: [
      { question: "What is an LLP?", answer: "A Limited Liability Partnership — a registered partnership structure where partners have limited liability, distinct from a traditional partnership firm." },
      { question: "How many partners does an LLP need?", answer: "A minimum of two, with at least two designated partners, one of whom must be resident in India." },
      { question: "Can an LLP raise funding from investors?", answer: "Not through equity shares — an LLP cannot issue shares, which makes it less suited to startups planning venture funding." },
      { question: "What documents are required?", answer: "PAN, Aadhaar and address proof of partners, registered office proof, and Digital Signature Certificates for designated partners." },
      { question: "Is an LLP Agreement mandatory?", answer: "Yes — it governs how the LLP operates, including profit-sharing and partner responsibilities, and is filed with the Registrar after incorporation." },
      { question: "How is an LLP different from a Private Limited Company?", answer: "An LLP generally has lower compliance requirements and no minimum capital rule, but cannot issue equity shares the way a private limited company can." },
    ],
    relatedServices: ["partnership-firm-registration", "private-limited-company", "digital-signature-certificate", "gst-registration", "msme-udyam-registration"],
    ctaDescription: "Tell us about your partners and business plans, and we'll confirm whether an LLP is the right fit before filing.",
  },
  {
    slug: "partnership-firm-registration",
    title: "Partnership Firm",
    categoryId: "business-registration",
    categoryLabel: "Business Registration & Incorporation",
    code: "REG-04",
    coverage: "existing",
    shortDescription:
      "Register a partnership firm with a proper partnership deed — a traditional structure for professional and family-run businesses.",
    heroHeadline: "A traditional structure, set up on solid documentation.",
    heroSupport:
      "We draft a clear partnership deed and complete the registration process, so responsibilities, profit-sharing and exit terms are settled upfront, not argued about later.",
    description: [
      "A partnership firm is a business run by two or more people who agree to share profits according to a partnership deed, governed by the Indian Partnership Act, 1932. It's one of the simplest ways for multiple people to run a business together.",
      "Registration is technically optional under the Act, but an unregistered firm loses several legal rights — including the ability to sue a third party or another partner to enforce the partnership deed — which makes registration worth doing properly.",
      "Gurur Consultancy drafts a partnership deed that reflects how the partners actually intend to work together, and completes the registration with the Registrar of Firms.",
    ],
    benefits: [
      "Simple and quick to set up compared to a company or LLP",
      "Clear, documented profit-sharing and responsibility terms in the deed",
      "A registered firm can sue and enforce its rights against third parties and other partners",
      "Lower compliance burden than a company structure",
    ],
    whoNeedsIt: [
      "Professional firms — such as consultancies, architects and small practices — with two or more partners",
      "Family-run businesses formalising how profits and responsibilities are shared",
      "Small businesses not yet ready for company or LLP-level compliance",
    ],
    eligibility: [
      "Requires a minimum of two partners, up to a maximum set by the Companies Act for unregistered partnerships",
      "Registration is optional but strongly advisable given the legal rights it preserves",
    ],
    documents: [
      "PAN and Aadhaar of all partners",
      "Address proof of the firm's place of business",
      "Partnership deed signed by all partners, typically on stamp paper",
      "Passport-size photographs of partners",
    ],
    documentsNote: "Commonly required documents may include:",
    process: [
      { title: "Consultation", description: "We understand how the partners intend to share profits, capital and responsibilities." },
      { title: "Deed Drafting", description: "We draft a partnership deed reflecting the agreed terms — capital contribution, profit ratio, roles and exit conditions." },
      { title: "Deed Execution", description: "The deed is executed by all partners, typically on appropriate stamp paper." },
      { title: "Firm Registration", description: "The firm is registered with the Registrar of Firms in the relevant state." },
      { title: "PAN Allotment", description: "PAN is obtained in the name of the firm for tax and banking purposes." },
    ],
    faqs: [
      { question: "Is partnership firm registration mandatory?", answer: "No, but an unregistered firm loses important legal rights — such as suing a third party to enforce a contract — so registration is strongly recommended." },
      { question: "What is a partnership deed?", answer: "The written agreement between partners covering capital contribution, profit-sharing ratio, roles, and what happens if a partner exits or the firm dissolves." },
      { question: "How many partners can a firm have?", answer: "A minimum of two — the upper limit for an unregistered/general partnership is set by law and confirmed at the time of drafting." },
      { question: "Are partners personally liable for the firm's debts?", answer: "Yes — unlike an LLP or company, partners in a general partnership firm have unlimited personal liability for the firm's obligations." },
      { question: "What documents are required?", answer: "PAN and address proof of partners, proof of the firm's place of business, and the executed partnership deed." },
      { question: "Can a partnership firm later convert to an LLP or company?", answer: "Yes, conversion is possible under prescribed procedures if the business later needs limited liability protection." },
    ],
    relatedServices: ["llp-registration", "proprietorship-registration", "gst-registration", "professional-tax-registration"],
    ctaDescription: "Tell us how you and your partners want to structure the business, and we'll draft the deed and complete the registration.",
  },
  {
    slug: "proprietorship-registration",
    title: "Proprietorship",
    categoryId: "business-registration",
    categoryLabel: "Business Registration & Incorporation",
    code: "REG-05",
    coverage: "existing",
    shortDescription:
      "Set up a sole proprietorship — the simplest business structure, with minimal compliance and fast setup.",
    heroHeadline: "The fastest way to start operating formally.",
    heroSupport:
      "We help you get the registrations a proprietorship actually needs — GST, MSME/Udyam and local licenses where applicable — so you can start invoicing and operating quickly.",
    description: [
      "A sole proprietorship is a business owned and run by a single individual, with no legal distinction between the owner and the business. It's the simplest and fastest way to start operating formally in India.",
      "There's no separate incorporation process for a proprietorship itself — what actually establishes it as a functioning, recognisable business is the combination of registrations it obtains, such as GST, Udyam/MSME registration, and any applicable local licenses.",
      "Gurur Consultancy helps identify exactly which registrations your specific proprietorship needs based on its activity, location and turnover, and completes them so you can start operating and invoicing.",
    ],
    benefits: [
      "Fastest and least expensive structure to start operating under",
      "Minimal ongoing compliance compared to a company or LLP",
      "Complete control — the owner makes all business decisions directly",
      "Straightforward to convert to a company or LLP later if the business grows",
    ],
    whoNeedsIt: [
      "Individual entrepreneurs starting a small business or service practice",
      "Freelancers and consultants who want to formalise invoicing and GST compliance",
      "Small local businesses — shops, trades, small manufacturing units",
    ],
    eligibility: [
      "Open to any individual Indian resident wanting to run a business in their own name or a trade name",
      "No minimum capital or formal incorporation process — establishment is evidenced through the registrations obtained (GST, Udyam, etc.)",
    ],
    documents: [
      "PAN and Aadhaar of the proprietor",
      "Proof of business address — rent agreement/NOC or utility bill",
      "Bank account proof in the business/proprietor's name",
      "Applicable trade or local license documents, where relevant to the activity",
    ],
    documentsNote: "Commonly required documents may include:",
    process: [
      { title: "Consultation", description: "We identify your business activity, location and turnover to determine which registrations you actually need." },
      { title: "GST Registration", description: "GST registration is filed if your turnover or activity requires it, or if you want it voluntarily." },
      { title: "MSME / Udyam Registration", description: "Udyam registration is filed to establish your MSME status and its associated benefits." },
      { title: "Local Licenses", description: "Shop Act/Gumasta or other local licenses are filed where your business location or activity requires them." },
      { title: "Bank Account Setup", description: "With the registrations in hand, you're positioned to open a current account in the business's name." },
    ],
    faqs: [
      { question: "Is there a separate 'proprietorship registration' certificate?", answer: "No single certificate — a proprietorship is established through the registrations it holds, such as GST and Udyam/MSME registration." },
      { question: "Is the owner personally liable for business debts?", answer: "Yes — there's no legal separation between the owner and the business, so liability is unlimited and personal." },
      { question: "What registrations does a proprietorship typically need?", answer: "This depends on the business, but commonly includes GST (if applicable) and MSME/Udyam registration, plus any local trade licenses." },
      { question: "Can a proprietorship register on GeM or bid for government tenders?", answer: "Yes, subject to the eligibility criteria of the specific tender or GeM category — proprietorships aren't excluded by default." },
      { question: "How long does it take to get operating?", answer: "Considerably faster than a company or LLP, since there's no incorporation filing — timelines depend on which registrations apply to you." },
      { question: "Can I convert my proprietorship to a company later?", answer: "Yes — many businesses start as a proprietorship and convert to an LLP or private limited company as they grow." },
    ],
    relatedServices: ["gst-registration", "msme-udyam-registration", "trade-license", "shop-establishment-gumasta-registration"],
    ctaDescription: "Tell us what your business does and where you operate, and we'll confirm exactly which registrations you need to get started.",
  },
  {
    slug: "section-8-company-registration",
    title: "Section 8 Company",
    categoryId: "business-registration",
    categoryLabel: "Business Registration & Incorporation",
    code: "REG-06",
    coverage: "existing",
    shortDescription:
      "Register a Section 8 Company — a non-profit entity with limited liability, for charities, foundations and social enterprises.",
    heroHeadline: "A formal, credible structure for non-profit work.",
    heroSupport:
      "We handle incorporation and the licensing that makes a Section 8 Company distinct from an ordinary company — so your non-profit is set up correctly from the start.",
    description: [
      "A Section 8 Company is a company registered under Section 8 of the Companies Act, 2013 for promoting charitable objects — such as commerce, art, education, research, social welfare or environmental protection — with limited liability for its members.",
      "Unlike an ordinary company, a Section 8 Company cannot distribute profits to its members as dividends; any income must be applied toward furthering its stated objects. This is what gives it credibility with donors, grant-makers and regulators.",
      "Gurur Consultancy manages the incorporation process, including the additional licensing step specific to Section 8 Companies, and can advise on the related 12A/80G tax-exemption registrations that most non-profits pursue alongside it.",
    ],
    benefits: [
      "Limited liability for members, like an ordinary private limited company",
      "Higher credibility with donors, grant-making bodies and government agencies than an unregistered trust or society in many contexts",
      "Formal corporate governance structure — board of directors, defined objects",
      "Eligible to apply for 12A and 80G tax-exemption registrations once incorporated",
    ],
    whoNeedsIt: [
      "Founders setting up a charitable foundation, NGO or social enterprise wanting a formal corporate structure",
      "Organisations planning to raise CSR funding, where a registered structure and later CSR-1 registration are typically expected",
      "Groups that want a more corporate governance structure than a trust or society offers",
    ],
    eligibility: [
      "Requires the same minimum director/shareholder structure as a private or public company, depending on the type chosen",
      "The company's objects must be genuinely charitable — commerce, art, science, education, research, social welfare, religion, or environmental protection — with profits applied only toward those objects",
      "Requires a specific license from the Registrar (via the incorporation process) confirming the non-profit purpose",
    ],
    documents: [
      "PAN and Aadhaar of proposed directors/members",
      "Detailed statement of the proposed charitable objects and projected income/expenditure",
      "Proof of registered office with NOC where applicable",
      "Digital Signature Certificates for proposed directors",
      "Draft MOA and AOA reflecting the non-profit objects",
    ],
    documentsNote: "Commonly required documents may include:",
    process: [
      { title: "Consultation", description: "We clarify your charitable objects and confirm a Section 8 Company is the right structure versus a trust or society." },
      { title: "DSC & Name Approval", description: "Digital Signature Certificates are obtained and the company name is reserved." },
      { title: "License & Incorporation Filing", description: "We prepare and file the incorporation application including the Section 8 license request with the Registrar." },
      { title: "MOA & AOA", description: "Objects and governance rules are documented in the Memorandum and Articles of Association." },
      { title: "PAN & TAN Allotment", description: "PAN and TAN are issued along with incorporation." },
      { title: "12A / 80G Guidance", description: "We advise on the follow-on 12A and 80G tax-exemption registrations most Section 8 Companies pursue next." },
    ],
    faqs: [
      { question: "What is a Section 8 Company?", answer: "A company registered under the Companies Act specifically for charitable objects, with limited liability and a restriction on distributing profits to members." },
      { question: "Can a Section 8 Company make a profit?", answer: "It can generate income, but that income must be applied toward its stated charitable objects rather than distributed to members as dividends." },
      { question: "How is this different from a Trust or Society?", answer: "A Section 8 Company follows the Companies Act's corporate governance framework, which many donors and regulators view as more transparent and structured than a trust or society, though all three are valid non-profit routes." },
      { question: "Do I need 12A and 80G registration too?", answer: "These are separate tax-exemption registrations most non-profits pursue after incorporation — we can advise on both once the company is registered." },
      { question: "What documents are required?", answer: "PAN and address proof of directors, a clear statement of charitable objects, and draft MOA/AOA reflecting those objects — the exact list is confirmed during consultation." },
      { question: "Can a Section 8 Company later receive CSR funding?", answer: "It can be eligible, subject to separately completing CSR-1 registration and meeting the corporate donor's own due-diligence requirements." },
    ],
    relatedServices: ["private-limited-company", "gst-registration", "digital-signature-certificate"],
    ctaDescription: "Tell us about the charitable objects you want to pursue, and we'll confirm the right structure and take the filing forward.",
  },
];
